version: 2

jobs:
  matejs_test:
    working_directory: ./matejs
    docker:
      - image: circleci/node:9.11.1
    steps:
      - run:
          name: Test
          command: npm run ci
      - store_artifacts:
          name: Copy code coverage
          command: './test-results.xml $CIRCLE_TEST_REPORTS/junit.xml'

workflows:
  version: 2
  test_matejs:
    jobs:
      - matejs_test
