version: 2

jobs:
  matejs_test:
    working_directory: ~/matejs/matejs
    docker:
      - image: circleci/node:9
    steps:
      - run:
          name: Test
          command: yarn run ci
      - store_artifacts:
          path: test-results.xml
          prefix: tests

workflows:
  version: 2
  test_matejs:
    jobs:
      - matejs_test
